version: '3.8'
services:
  chatbot:
    build: .
    ports:
      - "5000:5000"
      - "8501:8501"
    environment:
      - FLASK_APP=flag.py
      - FLASK_ENV=production
      - API_URL=http://localhost:5000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 3
